---
title: "Electromagnetism: Unit System"
---

**Tags**: [Electromagnetism](../tags/electro.qmd), [Physics](../tags/physics.qmd)

## Activity Introduction

In this course we typically think in meters. In the programming labs, the x and y variables are actually in pixel units and the width of the screen is 750 pixels. For example, if the position of the object (x) is less than zero or larger than 750, the object will move off of the screen. Typically the height of the screen is 500. If the vertical position of the object (y) is less than zero or larger than 500 the object will move off the screen.

How do we relate pixels to the typical meter units that we use in class? We have some options!

We could figure out how large each pixel actually is on your screen in meters and then multiply the x and y positions by this size. This involves a lot of multiplying and a lot of confusion about whether we are talking about meters or pixels. For example, we would have to multiply all the velocities by the pixel size to change the units from pixels per second to meters per second, and the same thing for the acceleration (to change it from pixels per second2 to meters per second2). Everyone's screen will have a slightly different pixel size. What a mess!

The simpler thing is to just think of pixels as meters and talk about velocities as meters per second and accelerations as meters per second squared. There is no harm in doing this! It just means that the screen (with the particle being accelerated between two plates) is showing something that is much larger than what actually appears on the screen. Since the screen is 750 pixels across, this means that you are looking down on something that is really 7.5 soccer fields across. This is a little bit weird to imagine but it is a lot simpler than the alternative.

## Links to Activity
* [Instructions for Electromagnetism: Unit System](https://www.asc.ohio-state.edu/orban.14/physics_coding/units.html)

