project:
  type: website
  output-dir: docs
  title: STEMcoding
  resources:
    - CNAME
    - vaxgame
    - bracket.html
    - qrcode.min.js
    - soccer.html
    - img/stemcoding_data_science_icon_2026.png
    - img/Ohio_State_University_at_Marion_Logo.png
    - img/OSU_Marion_logo.png
    - dimorphism.html
    - dimorphism2.html
    - how_we_fixed_the_ozone_layer.html
    - ozone-depleting-substances-index.csv
    - amarillo_TX_balloon_data.txt
    - wilmington_OH_balloon_data.txt
    
website:
  favicon: img/stemcoding_favicon_final.png
  navbar:
    title: false
    left:
      - text: '<img src="/img/STEMcoding_logo_transparent.png" alt="STEMcoding Logo" style="height: 38px; margin-top: -10px;">'
        href: index.qmd
      - about.qmd    
      - activities.qmd
      - href: people.qmd
        text: People
      - href: feed.qmd
        text: Feed
      - calendar.qmd
      - datascience.qmd
      - href: soccer.html
        text: Soccer 2026
      - publications.qmd
    tools:
      - icon: youtube
        href: https://www.youtube.com/STEMcoding
      - icon: instagram
        href: https://www.instagram.com/stemcoding/  
      - icon: facebook
        href: https://www.facebook.com/stemcodingproject
      - icon: mastodon 
        href: https://mastodon.social/@STEMcoding
      - icon: discord
        href: https://discord.gg/bsWgqcqwCE        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    sidebar:
      - id: main-sidebar
        contents:
          - section: "On this page"
            contents: auto
          - section: "Social Feed"
            contents: auto



