---
title: "Publications"
---

### 2025

<p><a href="https://dl.acm.org/doi/book/10.1145/3724411">Nutwell, E. and Badger, K. "Public Data in the Public Interest: A Spreadsheet-Based Project for High School Computing", Association for Computing Machinery (2025)</a>


<p><a href="https://doi.org/10.1162/99608f92.63a523ec">Badger, K., Nutwell, E. and Kulp, Jessica K. "Spreadsheet Data Science in K-12: An On-Ramp for the Future Data Literate Citizen" Harvard Data Science Review (2025)</a>

### 2024

<p><a href="https://doi.org/10.1145/3626253.3635580">Orban, C. “Blurring the Boundaries between Science, Math, and Computer Science” Proceedings of the 55th ACM Technical Symposium on Computer Science Education (2024)</a>

<p><a href="https://dl.acm.org/doi/10.1145/3626253.3635589">Nutwell, E., Badger, K. and Kulp, J. T. "Data for Healthy Communities: A Public Interest Pilot Course Designed to Develop K-12 Data Literacy" Proceedings of the 55th ACM Technical Symposium on Computer Science (2024)</a>

### 2023

<p><a href="https://arxiv.org/abs/2206.07909">Orban, C., Zimmerman, S., Kulp, J. T., Boughton, J., Perrico, Z., Rapp, B., Teeling-Smith, R. “Methods to Simplify Object Tracking in Video Data” The Physics Teacher, 61, 576-579 (2023)</a>

### 2020

<p><a href="https://arxiv.org/abs/1907.08079">Orban, C. and Teeling-Smith, R. ``Computational Thinking in Introductory Physics'' The Physics Teacher (2020)</a>

### 2018

<p><a href="https://doi.org/10.1119/1.5058449">Orban, C., Teeling-Smith, R. M., Smith, J. R. H., and Porter, C. D. "A Hybrid Approach for Using Programming Exercises in Introductory Physics", 2018, American Journal of Physics </a>

### 2017

<p><a href="https://arxiv.org/abs/1707.00185">Orban, C., Porter, C. D., Brecht, N. K., Teeling-Smith, R. M., Harper, K. A., "A novel approach for using programming exercises in electromagnetism coursework" PERC 2017</a>


